MQTT_ADDRESS = '192.168.161.89'
MQTT_PORT = 1883
MQTT_TIMEOUT = 60

SIMULATOR_SENSORS_PATTERN = 'sensors_group/collector/'
WEIGHTS_FILE = 'weights.yaml'

NUMBER_OF_SENSORS = 5
DESOLATED_SENSORS = [3,4]
