{
 "title": "IoT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n|> range(start:-1h)\r\n|> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\" or r._field == \"sensor_name\" )\r\n|> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> group()\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Current Month Total Power Usage Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n|> range(start:-24h)\r\n|> filter(fn: (r) => r[\"_field\"] == \"power_usage\")\r\n|> drop(columns: [\"_start\", \"_stop\"])\r\n|> group()\r\n|> sum()\r\n  |> map(fn: (r) => ({ r with _value: float(v:r._value) * 0.77 }))\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Currently Active Sensors [last 5m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n|> range(start: -5m, stop: now())\r\n|> keep(columns: [\"sensor_name\"])  \r\n|> distinct(column: \"sensor_name\")\r\n|> group()\r\n|> count()\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cumulative Power Usage [last 24h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n|> range(start:-24h)\r\n|> filter(fn: (r) => r[\"_field\"] == \"power_usage\")\r\n|> drop(columns: [\"_start\", \"_stop\"])\r\n|> group()\r\n|> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Cumulative Lighting Time [last 24h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n|> range(start:-24h)\r\n|> filter(fn: (r) => r[\"_field\"] == \"lighting_time\")\r\n|> drop(columns: [\"_start\", \"_stop\"])\r\n|> group()\r\n|> cumulativeSum()"
    }
   ]
  }
 ]
}