BROKER_HOST = "localhost"
BROKER_PORT = 1883
ENCODING = 'utf-8'
BROKER_DISCOVERY_TOPIC = "discovery/hello"
BROKER_DYNAMIC_SECURITY_TOPIC = "$CONTROL/dynamic-security/v1"
BROKER_CONFIGURATION_TOPIC = "discoverer/config/{udid}"
BROKER_ADMIN_LOGIN = "adminLogin"
BROKER_ADMIN_PASSWORD = "adminPassword"

POSTGRESQL_DB_HOST = "127.0.0.1"
POSTGRESQL_DB_PORT = 5432
POSTGRESQL_DB_NAME = "postgres"
POSTGRESQL_DB_USERNAME = "postgres"
POSTGRESQL_DB_PASSWORD = "admin123456"
POSTGRESQL_DB_URL = f"postgresql+psycopg2://{POSTGRESQL_DB_USERNAME}:" + \
                    f"{POSTGRESQL_DB_PASSWORD}@" + \
                    f"{POSTGRESQL_DB_HOST}/{POSTGRESQL_DB_NAME}"
