{
 "title": "IoT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sensors activity history",
   "type": "state-timeline",
   "description": "History of states of sensor groups in the network",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\r\n|> range(start: -7d, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] =~ /sensor*/ and r._field == \"is_active\")\r\n|> set(key: \"_field\", value: \"status\")\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Sensors/Lamps settings",
   "type": "table",
   "description": "Settings of all sensors in network",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  devices.id,devices.UDID,devices.MAC,devices.longitude,devices.latitude,devices.version_id,groups.configuration -> 'lower_threshold' AS lower_bound, groups.configuration -> 'upper_threshold' AS upper_bound, devices.group_id \nFROM devices \nINNER JOIN groups ON groups.id=devices.group_id;\n"
    }
   ]
  },
  {
   "title": "Currently Active Sensors [%]",
   "type": "gauge",
   "description": "% of active sensors from last hour",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\r\n|> range(start: -1h, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"sensors_stats\" or r.field == \"active_lanterns_ratio\")\r\n|> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Sensors/Lamps groups settings",
   "type": "table",
   "description": "Settings of group of sensors/lamps",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, description, client_id, groups.configuration -> 'lower_threshold' AS lower_bound, groups.configuration -> 'upper_threshold' AS upper_bound, quantity\nFROM groups;\n"
    }
   ]
  },
  { "title": "Alarms", "type": "alertlist", "description": "Alarms in sensors network", "gridPos": { "h": 10, "w": 18, "x": 0, "y": 27 } },
  {
   "title": "Map of asensors",
   "type": "geomap",
   "description": "Location of sensors",
   "gridPos": { "h": 23, "w": 18, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  devices.latitude, devices.longitude, devices.id,devices.UDID,devices.MAC, devices.group_id, groups.configuration -> 'lower_threshold' AS brightness_lower_bound, groups.configuration -> 'upper_threshold' AS brightness_upper_bound\nFROM devices \nINNER JOIN groups ON groups.id=devices.group_id;\n\n"
    }
   ]
  }
 ]
}