mosquitto:
  image: eclipse-mosquitto
  container_name: mosquitto
  volumes:
    - /etc/mosquitto:/mosquitto/config
  ports:
    - 1883:1883
    - 9001:9001
collector:
  image: collector
  container_name: collector
